name: Find Gradle project

on:
  workflow_dispatch:

jobs:
  find:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find Gradle files
        run: |
          echo "CURRENT DIRECTORY:"
          pwd
          
          echo ""
          echo "ROOT CONTENT:"
          ls -la
          
          echo ""
          echo "GRADLE FILES:"
          find . -type f \( -name "build.gradle" -o -name "build.gradle.kts" -o -name "settings.gradle" -o -name "settings.gradle.kts" -o -name "gradlew" \) -print
